# Generated by Django 3.0.8 on 2020-07-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_auto_20200724_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermood',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
