# Generated by Django 3.0.8 on 2020-07-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_usermood_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermood',
            name='streak',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
